<?php

/**
 * @file
 * Contains hello.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hello_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hello module.
    case 'help.page.hello':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}


function template_preprocess_produit_entity(array &$variables) {
  // Fetch ProduitEntity Entity Object.
  $produit_entity = $variables['elements']['#produit_entity'];

  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}


/**
 * Implements hook_theme().
 */
function hello_theme() {

   $theme['hello_page'] = [
      'variables' => ['content' => NULL  ],
      'template' => 'produit_entity'
    ];

return $theme;

}
